### ISSUE TITLE
Game crashes when loading a resource pack (1.18.1)

### ISSUE THREAD

**Issue by Seanniex** [Fuzss/puzzleslib#1]
When ever I load a resource pack the game crashes when Puzzlelib and GoldenAgeCombat is installed. Without the puzzlelib and GoldenAgeCombat loading a resource pack seems to be working fine

I also attached the crash report
[crash-2022-03-01_21.27.10-client.txt](https://github.com/Fuzss/puzzleslib/files/8161929/crash-2022-03-01_21.27.10-client.txt)

**Comment by Fuzss** [comment]
This is caused by Golden Age Combat.

https://github.com/Fuzss/goldenagecombat/issues/8
