### ISSUE TITLE
[Crash]: Server crashing in world generation

### ISSUE THREAD

**Issue by pewblaze** [Fuzss/puzzleslib#10]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.1

### Mod Version (Required)

PuzzlesLib-v4.1.2-1.19.1-Fabric.jar

### Notes (Required)

After starting the server & generating a new game it crashes.

### Crash Report (Required)

https://gist.github.com/pewblaze/b83b4e8000fd6ca537acd76023d7824d

### latest.log (Optional)

https://gist.github.com/pewblaze/2c2ed2333e25b802b65f64e686909ca5

**Comment by Fuzss** [comment]
Thanks, fixed in v4.1.4.
