### ISSUE TITLE
[Crash]: Failure to execute main entrypoint stage

### ISSUE THREAD

**Issue by kualatoni** [Fuzss/puzzleslib#101]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

20.4.0

### Other Mods Involved (Required)

Yes

### Notes (Required)

According to the crash report: "Could not execute entrypoint stage 'main' due to errors, provided by 'easymagic'." I have no idea what could be causing this.

### Crash Report (Required)

https://gist.github.com/kualatoni/5e034d94356578ee7a4d952300713f87

### latest.log (Optional)

https://gist.github.com/kualatoni/5709930fd7af79d6375e335954597bce

**Comment by kualatoni** [comment]
After launching repeatedly, I can confirm this is reproduceable

**Comment by Fuzss** [comment]
Report this to malilib.
