### ISSUE TITLE
[Crash]: Crash on switching to a bundle with items

### ISSUE THREAD

**Issue by ChromaPIE** [Fuzss/puzzleslib#106]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

PuzzlesLib-v8.1.18-1.20.1-Fabric

### Other Mods Involved (Required)

⸺

### Notes (Required)

Title
bundle is the vanilla datapack one

### Crash Report (Required)

https://mclo.gs/j3OcR6X

**Comment by Fuzss** [comment]
Please report this here: https://github.com/juancarloscp52/BedrockIfy/issues
The issue requires Bedrockify & Easy Shulker Boxes to be reproduced, has nothing to do with Puzzles Lib.

**Comment by Nuzza** [comment]
To solve this, disable the mixin "client.features.heldItemTooltips" in Bedrockify settings and reload your game:

![image](https://github.com/user-attachments/assets/ba8ce519-f379-42fe-9994-b94e61170480)
