### ISSUE TITLE
[Crash]: The current puzzleslib crashes on game initialisation

### ISSUE THREAD

**Issue by Grumpey102** [Fuzss/puzzleslib#11]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.1

### Notes (Required)

Hey, 

I tried to start the game but it wouldn't, didn't come into the main menu. It could also be the mod [Pick Up Notifier](https://www.curseforge.com/minecraft/mc-mods/pick-up-notifier), as the crash report suggests ("provided by pickupnotifier"), I don't know.

Cheers,
Grumpey

### Crash Report (Required)

https://gist.github.com/Grumpey102/f02b25a7d2e43d43af0b40f9d81c69c8

### latest.log (Optional)

https://gist.github.com/Grumpey102/90f2f9f79adc8d997f07f876cfc33baf

**Comment by Fuzss** [comment]
Fixed in latest version of Pick Up Notifier.
