### ISSUE TITLE
[Crash]: Magma and Fire Blocks caused boot-up crash

### ISSUE THREAD

**Issue by SpinWin** [Fuzss/puzzleslib#111]
### Mod Loader (Required)

Forge

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

v.20.4.42

### Other Mods Involved (Required)

Yes

### Notes (Required)

Game crashes instantly when clicking 'Play' button on Launcher. 

### Crash Report (Required)

https://gist.github.com/SpinWin/fb9544880026b6ac4b0bb847f154d115

**Comment by Fuzss** [comment]
Caused by this: https://github.com/03-JS/Extra-Enchantments-and-Curses/blob/1.20.x-Forge/src/main/java/net/js03/extraenchantments/mixin/MagmaBlockMixin.java
Report to them.

**Comment by SpinWin** [comment]
I read the crash report many times and the only thing named was PuzzlesLib, so I posted here. I'm not smartbrained enough to know where you got that other mod's name from.
