### ISSUE TITLE
[Bug]: java.lang.NullPointerException: charge is null when using bow

### ISSUE THREAD

**Issue by Metaloul** [Fuzss/puzzleslib#112]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

20.4.43

### Other Mods Involved (Required)

No

### Notes (Required)

Hello ! I don't use github normally so i hope my report is good.

I'm running my server on Archlight on version 1.0.3.

Each time i use a bow, i got the charge is null error in the console. I've tried downgrading the version etc but the problem was still present. Dunno if it's something that can be fixed on your side or not so i prefer to tell you.

That's the only bug i've found for now related to Puzzles

### latest.log (Required)

https://pastebin.com/f9gT5taG

**Comment by Fuzss** [comment]
Hmm, I'm not so sure about this one. Archlight does have an `@Overwrite` on that method, which definitely doesn't help.

**Comment by Metaloul** [comment]
AH, ok, i see. I've opened an issue on the Archlight repo too so I will wait for author's answer. That's weird because it's the only issue that I got.

**Comment by Metaloul** [comment]
Issue was coming from Archlight, the dev just fixed the issue. Thanks !
