### ISSUE TITLE
Create map crash[Crash]: 

### ISSUE THREAD

**Issue by zc1108aaa** [Fuzss/puzzleslib#114]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

1.20

### Other Mods Involved (Required)

No

### Notes (Required)

[latest.log](https://github.com/Fuzss/puzzleslib/files/15448616/latest.log)
1
[crash-2024-05-27_02.57.00-client.txt](https://github.com/Fuzss/puzzleslib/files/15448618/crash-2024-05-27_02.57.00-client.txt)

### Crash Report (Required)

1

**Comment by Fuzss** [comment]
Report this to the chimes mod.
