### ISSUE TITLE
[Bug]: FoV Effects modifier not applying properly

### ISSUE THREAD

**Issue by Tenuuu** [Fuzss/puzzleslib#119]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

21.0.4

### Other Mods Involved (Required)

Yes

### Notes (Required)

Upon modifying the "FOV Effects" slider in the accessibility settings, notice how there is no change to the FOV effects and that they stay at 100% unless the slider is set to off. Upon disabling the mod, the setting works properly

### latest.log (Required)

https://gist.github.com/Tenuuu/547f34421e6a3122d9595ca7a7a33f04

**Comment by Fuzss** [comment]
Thanks, fixed in v21.0.5. Won't backport to 1.24 which is also affected, support for that has been dropped.

**Comment by Tenuuu** [comment]
> Thanks, fixed in v21.0.5. Won't backport to 1.24 which is also affected, support for that has been dropped.

Do you mean 1.20 or am I misunderstanding?

**Comment by Fuzss** [comment]
I meant 1.20.4.
1.20.1 doesn’t have this issue.
