### ISSUE TITLE
[Bug]: wrong version uploaded to curseforge and modrinth

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Fuzss/puzzleslib#12]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.1

### Mod Version (Required)

v4.2.1 and v4.2.2

### Notes (Required)

Current behavior: The website says 1.19.1-1.19.2, but when I install it my client says it needs the fabric API required for 1.19.2.

Steps to reproduce:

Install on 1.19.1
Launch Minecraft
crashes
Expected: If it says 1.19.1-1.19.2 it should work. otherwise, it just confuses mod installers

**Comment by Fuzss** [comment]
Fabric Api 0.60.0+1.19.2 works on 1.19.1, too. All my mods work on 1.19.1 and 1.19.2, I specifically tested this.
If you get a crash somehow please provide the crash report.

**Comment by Aces-and-Jacks** [comment]
https://pastebin.com/aUiPiB3w
