### ISSUE TITLE
[Crash]: Neoforge 21.0.68 update crashes game on launch due to event entities naming change

### ISSUE THREAD

**Issue by ffuentesm** [Fuzss/puzzleslib#120]
### Mod Loader (Required)

NeoForge

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

21.0.8

### Other Mods Involved (Required)

Yes

### Notes (Required)

launch the game wiht the mod in the latest neoforge version
![image](https://github.com/Fuzss/puzzleslib/assets/44974827/ed1e4c2a-6186-47fc-8b54-6deb18afa4bd)

### Crash Report (Required)

https://pastebin.com/Tk9DPANQ

**Comment by Fuzss** [comment]
Fixed in v21.0.9, thanks!
