### ISSUE TITLE
[Bug]: Mixin Conflict Kiwi

### ISSUE THREAD

**Issue by Krimatoria** [Fuzss/puzzleslib#121]
### Mod Loader (Required)

Forge

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

PuzzlesLib-v8.1.21-1.20.1-Forge.jar

### Other Mods Involved (Required)

Yes

### Notes (Required)

https://github.com/Snownee/Kiwi/issues/61 - See
Something is wrong with the mixins.

### latest.log (Required)

https://gist.github.com/Krimatoria/4dadaefbddf2af3e7b4337b83514c846

**Comment by Fuzss** [comment]
I can't really find anything pointing at Puzzles Lib in there.

**Comment by Krimatoria** [comment]
> I can't really find anything pointing at Puzzles Lib in there.

![image](https://github.com/user-attachments/assets/7bf463e1-360b-4ecc-8586-ecfed517fa29)
I just saw this mention in the log, that's why I marked you. I don't understand much about it, at least I can translate some mistakes)

**Comment by Fuzss** [comment]
Yeah this isn’t related in any way.
