### ISSUE TITLE
[Crash]: [1.21] NeoForge latest version crash with Puzzles Lib

### ISSUE THREAD

**Issue by Periam** [Fuzss/puzzleslib#122]
### Mod Loader (Required)

NeoForge

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

PuzzlesLib-v21.0.15-1.21-NeoForge

### Other Mods Involved (Required)

No

### Notes (Required)

Added the mod to the MC using Curse  and launched the game.

### Crash Report (Required)

https://gist.github.com/Periam/28a07bc4a03350559c2af6ef9594d9ea

### latest.log (Optional)

https://gist.github.com/Periam/6ba2126e3d7152c84b17b4e5fd5b887a

**Comment by Fuzss** [comment]
Fixed in v21.0.17, thanks!
