### ISSUE TITLE
[Crash]:  I cannot start minecraft with both PuzzlesLib and ForgeConfigAPIPort, but without PuzzlesLib I can

### ISSUE THREAD

**Issue by darcpyka** [Fuzss/puzzleslib#125]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

21.0.18

### Other Mods Involved (Required)

Yes

### Notes (Required)

I can start minecraft with only ForgeConfigAPIPort, but with PuzzlesLib mod combined my client would crash showing it as "unexpected error". I've tested both mods separately and redownloaded them and the issue would still remain. Both mods are for fabric, 1.21.

### Crash Report (Required)

https://gist.github.com/DarcPika/dff10674cd6996e8cf46b8abea471f01

**Comment by Fuzss** [comment]
Update Forge Config Api Port.

**Comment by darcpyka** [comment]
wdym? i installed the latest version of both mods already?

**Comment by Fuzss** [comment]
In that case please upload a valid latest.log, the link you included leads nowhere.

**Comment by darcpyka** [comment]
the issue isnt even concluded why did u close it?

**Comment by darcpyka** [comment]
my condolences
it seems like the reason causing the link not working is that i changed my username
heres the link fixed https://gist.github.com/darcpyka/dff10674cd6996e8cf46b8abea471f01

**Comment by Fuzss** [comment]
The error is from Friends&Foes.

**Comment by darcpyka** [comment]
i see, but it still crashes after ive deleted that mod from my client.
heres the link
https://gist.github.com/darcpyka/0d6739c3ef549ee128a6ec69e4973563

**Comment by Fuzss** [comment]
Now that's EMI. I'm also not sure if it has something to do with Lunar, you should probably seek them for more help.

**Comment by darcpyka** [comment]
weird.. My game run perfectly fine until i added your mods... no offense btw i really like ur mods its just that my client isnt doing its job

**Comment by darcpyka** [comment]
hey fuzss, does ur mod have any conflicts with other mods
