### ISSUE TITLE
[Bug]: Unable to make a world with latest neoforge puzzleslib version

### ISSUE THREAD

**Issue by VaporeonScripts** [Fuzss/puzzleslib#132]
### Mod Loader (Required)

NeoForge

### Minecraft Version(s) (Required)

1.21.1

### Mod Version(s) (Required)

latest

### Other Mods Involved (Required)

Yes

### Notes (Required)

latest version of puzzles lib for neoforge causes the game to crash when trying to make a world, the only working version is the one before the latest

### latest.log (Required)

https://mclo.gs/oQKSo02

**Comment by Fuzss** [comment]
EasyShulkerBoxes isn't updated for 1.21.1 yet.

**Comment by VaporeonScripts** [comment]
alright
