### ISSUE TITLE
[Suggestion]: Puzzles Lib - Previous versions Prior 1.16

### ISSUE THREAD

**Issue by AwayBarbecue619** [Fuzss/puzzleslib#134]
### Mod Loader (Optional)

Forge

### Minecraft Version(s) (Optional)

MC Versions 1.12.2

### Mod Version(s) (Optional)

MC Versions 1.12.2

### Suggestion (Required)

Better Animations Collection requires Puzzle Lib. Better Animations offers the version 1.9.4 - 1.21 but right now Puzzle Lib only offers versions MC versions 1.16.5 - 1.20.1. If is possible to get the 1.12.2 versions? do I even need this to run in the older version?
Thank you for your time

**Comment by Fuzss** [comment]
You don't.

**Comment by AwayBarbecue619** [comment]
I won't need Puzzles Lib?
