### ISSUE TITLE
[Crash]: 1.21.1 neoforge crash on startup

### ISSUE THREAD

**Issue by NancalaStarry** [Fuzss/puzzleslib#136]
### Mod Loader (Required)

NeoForge

### Minecraft Version(s) (Required)

1.21.1

### Mod Version(s) (Required)

PuzzlesLib-v21.1.10-1.21.1-NeoForge

### Other Mods Involved (Required)

Yes

### Notes (Required)

Crash on startup

### Crash Report (Required)

https://mclo.gs/14uSidI

### latest.log (Optional)

https://mclo.gs/DkmTJT5

**Comment by Fuzss** [comment]
Update Bag of Holding.
