### ISSUE TITLE
[Crash]: ConcurrentModificationException

### ISSUE THREAD

**Issue by CaoTrongThang** [Fuzss/puzzleslib#145]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

8.1.25

### Other Mods Involved (Required)

⸺

### Notes (Required)

I keep getting random crashes, i think it's because of your mod:
the class 757
AbstractInvocationHandler
EventFactory

### Crash Report (Required)

https://gist.github.com/CaoTrongThang/cdf543e0281f9d1025977800ce6ab243

**Comment by Fuzss** [comment]
Don't see any hint there at Puzzles Lib being involved. Architectury might be though.
