### ISSUE TITLE
[Bug]: Clearing effects causes error, disconnect, or client crash

### ISSUE THREAD

**Issue by larz101** [Fuzss/puzzleslib#148]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21.3

### Mod Version(s) (Required)

Fabric API 0.109.0, Forge Config API Port 21.3.2, PuzzlesLib 21.3.5

### Other Mods Involved (Required)

Yes

### Notes (Required)

Clearing effects on singleplayer causes either a crash or an error if the player has any potion effects. When clearing effects via command (_/effects clear_), the command produces the error: **An unexpected error occurred trying to execute that command**. When clearing effects via drinking a milk bucket, the client crashes. 
When tested on a server with PuzzlesLib on the client and server, the _/effects clear_ command will give the same error. However, drinking a milk bucket will immediately disconnect the client.

This is reproducible only if PuzzlesLib is installed. Removing PuzzlesLib causes normal vanilla behavior, and does not error/crash the client. Attached is the log for the client crash when drinking a milk bucket in a singleplayer world.

### latest.log (Required)

https://pastebin.com/qbSw7uRU

**Comment by Fuzss** [comment]
Thanks! Fixed in v21.3.8.
