### ISSUE TITLE
[Crash]: Baby horses crash game w/ Horse Stonks installed

### ISSUE THREAD

**Issue by antieksi** [Fuzss/puzzleslib#149]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

v21.0.28

### Other Mods Involved (Required)

Yes

### Notes (Required)

1. Install [Horse Stonks](https://modrinth.com/mod/horse-stonks)
2. Try breeding horses 
3. Game crashes on the same tick that baby horse spawns

As Horse Stonks is a single mixin mod that is not even actively maintained (and even if it is the one that is causing the issue), I presume that it should be fixed on Puzzles Lib side.

Logs below may include some Russian text, so to be clear:
> Remove the entity ~~'Лошадь'~~ 'Horse' at the location 20.22, 177, 12.17.

### Crash Report (Required)

https://mclo.gs/TAfmHLS

### latest.log (Optional)

https://mclo.gs/7bVvtA5

**Comment by Fuzss** [comment]
The issue has nothing to do with Puzzles Lib.
