### ISSUE TITLE
[Suggestion]: Make Libary Future Version functional.

### ISSUE THREAD

**Issue by gamerjungexd** [Fuzss/puzzleslib#152]
### Mod Loader (Optional)

⸺

### Minecraft Version(s) (Optional)

1.21.3

### Mod Version(s) (Optional)

21.3.10

### Suggestion (Required)

Instead of hardcode the modversion, make it that its only a min-version. You already support higher fabric loaders etc, but not higher minecraft versions. Add instead of `"minecraft": "${minecraftVersion}",` please "minecraft": ">=${minecraftVersion}", or restrict it only to upgrades in the MinorNumber and not for the Last/Patch Number.

**Comment by Fuzss** [comment]
That's intentional, there are always significant changes across even minor Minecraft releases now that require a proper port.
