### ISSUE TITLE
Compatability is completely stupid.

### ISSUE THREAD

**Issue by JadeHeartDeer** [Fuzss/puzzleslib#17]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.3.12

### Notes (Required)

There is literally compatibility layers or any compatibility at all with Forge fabric API. And The forge API page has no link to a 1.19.2 compatible dependency, needed to run this library in the first place. IT IS DIRE that this can be found properly on the forge page as it is a forge API. Meaning the puzzleslib Is completely redundant. Why make a 1.19.2 version if there is no compatible API for it?!?
![image](https://user-images.githubusercontent.com/105595137/210185643-be54733b-7396-405c-8d45-16d02626bd2c.png)
![Screenshot 2023-01-01 154113](https://user-images.githubusercontent.com/105595137/210185662-d5c4f482-8ef6-45c2-ba71-a938abf64825.png)

### Crash Report (Required)

https://gist.github.com/JadeHeartDeer/43d7d948927d08f69c5e6548e5894bd2#file-gistfile1-txt

**Comment by Fuzss** [comment]
https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric/files/all?filter-status=1&filter-game-version=2020709689%3A9366
