### ISSUE TITLE
[Crash]: Using with optifine crashes the game

### ISSUE THREAD

**Issue by Meawerful** [Fuzss/puzzleslib#18]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.3.12-1.19.2-Fabric

### Notes (Required)

Just install OptiFine and puzzleslib together
this my OptiFine version: preview_OptiFine_1.19.2_HD_U_I1_pre4 

### Crash Report (Required)

https://gist.github.com/Meawerful/d7d2444173119d82624f3ca151fe446e

### latest.log (Optional)

https://gist.github.com/Meawerful/ca6c5b75d9ce59e88b602837f731ff55

**Comment by Fuzss** [comment]
Please remove Puzzles Lib and install this mod and tell me if it still crashes: https://www.curseforge.com/minecraft/mc-mods/cardinal-components/files/3954769

(only install the main file called `cardinal-components-api-5.0.2.jar`, don't download any of the additional files)

**Comment by Meawerful** [comment]
> 

it still crashed 
https://gist.github.com/Meawerful/7c0f9411a1516e6b8e8a6d8645a722fd

**Comment by Fuzss** [comment]
You should report this to Cardinal Components, it's an issue between their mod and OptiFine. I simply use the api.
