### ISSUE TITLE
[Crash]: Going on Single Player worlds With optifine

### ISSUE THREAD

**Issue by OskarSl66** [Fuzss/puzzleslib#25]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

1.18.2

### Notes (Required)

1. install Forge and Optifine 1.18.2
2. Instal Minecraft Puzzles Lib 1.18.2 Forge
3. Start up the Game 
4. Go to Singleplayer and choose any world
5. *Crashes*

The Emd 

### Crash Report (Required)

https://gist.github.com/OskarSl66/ee01748d9492e68dcb29ad65a24f336c

**Comment by Fuzss** [comment]
I'm unable to reproduce the issue with the minimal set of mods. Also the exception cause seems unrelated to Puzzles Lib, looks more like an outdated version of Forge / OptiFine. Also Puzzles Lib has had a major overhaul for the 1.18.2 recently.

Please try again with all the latest versions and reopen this issue if you are able to reproduce the original problem.
