### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by caaaat1** [Fuzss/puzzleslib#26]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

3.3.6

### Notes (Required)

asks to install version 3.3.0 or newer, but when I do it still shows the same message. I've tried multiple versions, but it still doesn't work

### Crash Report (Required)

https://paste.gemwire.uk/view/439b4213

**Comment by Fuzss** [comment]
you downloaded the wrong jar, this is the correct one
https://www.curseforge.com/minecraft/mc-mods/puzzles-lib/download/4412547

**Comment by caaaat1** [comment]
the same error message still pops up. are there any other solutions?

**Comment by Fuzss** [comment]
i fixed the link try again

**Comment by caaaat1** [comment]
worked perfectly. thank you for the help
