### ISSUE TITLE
[Crash]: wolves kill sheep crash

### ISSUE THREAD

**Issue by harithmf** [Fuzss/puzzleslib#29]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.3

### Mod Version (Required)

5.0.10

### Notes (Required)

wolf kill sheep, game crash

### Crash Report (Required)

https://gist.github.com/harithmf/fbd12ccfbd8027447b11037bf371d322

**Comment by Fuzss** [comment]
Fixed in v5.0.11, thansk!
