### ISSUE TITLE
[Bug]: Villager discount strikethrough rendering below text layer

### ISSUE THREAD

**Issue by zSoulweaver** [Fuzss/puzzleslib#31]
### Mod Loader (Required)

Quilt

### Minecraft Version (Required)

1.19.3

### Mod Version (Required)

5.0.12

### Notes (Required)

Red strike through for villager discounts is appearing behind the text instead of in front of the text. Log attached is with a bunch of other mods enabled, but issue occurs with only Puzzles enabled.

Vanilla:
![](https://cdn.discordapp.com/attachments/917550806922846299/1089483762670260307/image.png)

w/ Puzzles Enabled
![](https://cdn.discordapp.com/attachments/917550806922846299/1089483762892550184/image.png)

### latest.log (Optional)

https://gist.github.com/zSoulweaver/9326ad75e83d0ceafd3ab1142680d95d

**Comment by Fuzss** [comment]
Thanks, fixed in v5.0.14.
