### ISSUE TITLE
[Crash]: Incompatibility with Optifine in Fabric

### ISSUE THREAD

**Issue by Arkadyaaa** [Fuzss/puzzleslib#34]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.3.12

### Notes (Required)

Mod versions:

OptiFine_1.19.2_HD_U_I1
optifabric-1.13.16
PuzzlesLib-v4.3.12-1.19.2-Fabric
ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric
fabric-api-0.76.0+1.19.2

Game instantly crashes on launch

### Crash Report (Required)

game doesn't generate crash report

### latest.log (Optional)

https://gist.github.com/Arkadyaaa/11a2f94cbf2b285325eb186885c1b72d

**Comment by Fuzss** [comment]
See #18.
