### ISSUE TITLE
[Crash]: [Render thread/ERROR] [Puzzles Lib/]: Calling server config when it is not yet available! This is a bug! Message: Config data is missing java.lang.Exception: Config not yet available

### ISSUE THREAD

**Issue by Minebrah** [Fuzss/puzzleslib#37]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

PuzzlesLib-v4.4.0-1.19.2-Forge

### Notes (Required)

1. Press keybind
2. Crash

### Crash Report (Required)

https://gist.github.com/Minebrah/573792132bd2b16b0bab34f248c24ba7

### latest.log (Optional)

https://gist.github.com/Minebrah/ae9a4f509ab790e63b0c4f4e34506008

**Comment by Fuzss** [comment]
Those logs don't seem to be the correct ones, the issue you mentioned in the title does not occur in there. Also the logs don't indicate a crash, just a bunch of warnings.

Can you provide logs with the issue from the title?
