### ISSUE TITLE
[Crash]: Mods calling Forge API on fabric.

### ISSUE THREAD

**Issue by VsUK** [Fuzss/puzzleslib#38]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.4.0

### Notes (Required)

I've got TradingPost fabric mod which calls for a Forge API & the error is caused by Puzzles Lib Fabric. I've shared the error with server modders for Fabric & they've identified the cause is Puzzles Lib.

### Crash Report (Required)

https://gist.github.com/VsUK/6035c8b0ebf8c42862d954d5eb143f2b

**Comment by Fuzss** [comment]
Install the latest version of Forge Config Api Port which is v4.2.11. the one bundled with Twilight Forest is outdated.
