### ISSUE TITLE
[Crash]: During normal gameplay MC crashes / Error message reported puzzlelib

### ISSUE THREAD

**Issue by Cape-City** [Fuzss/puzzleslib#40]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.3

### Mod Version (Required)

5.0.26

### Notes (Required)

Hi Fuzs,

i was just flying around in creative mode and the world crashes after serveral minutes of gameplay.
When i load the game again, the world crashes directly after entering the world.
After rollback to PuzzlesLib-v5.0.24-1.19.3-Fabric.jar i was able to load into my world again.

After updating again to the latest version the crash happens again:

![grafik](https://github.com/Fuzss/puzzleslib/assets/122229367/be85b7e9-3424-4049-b1a7-ca1690ab0501)

### Crash Report (Required)

https://gist.github.com/Cape-City/aba9985c31c3cb86180ef3c250cb14e3

### latest.log (Optional)

https://gist.github.com/Cape-City/02b1658af19638e4a99007eea50b5ef4

**Comment by Fuzss** [comment]
Thanks for reporting! Fixed in v5.0.27.

**Comment by Cape-City** [comment]
That was fast ;) Fix is working!
