### ISSUE TITLE
[Crash 1.19.2]: Crash on new Version with Puzzleslib 4.4.1

### ISSUE THREAD

**Issue by suerion** [Fuzss/puzzleslib#45]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.4.1

### Notes (Required)

After Updating Puzzleslib, trying to join the server on 1.19.2, with Easy Magic, it crash instantly

![grafik](https://github.com/Fuzss/puzzleslib/assets/55131959/855b82ef-e42d-46a1-9c75-83b16c78ff5c)

And Also Fastload will not load anymore, it says, fastload is only for 1.20. 
With puzzleslib 4.4.0 it works nromal

### Crash Report (Required)

No Crash Report, only Fabric Loader

**Comment by Fuzss** [comment]
I need your latest.log and also make sure you installed the Fabric version and not Forge.

**Comment by suerion** [comment]
[2023-06-13-5.log](https://github.com/Fuzss/puzzleslib/files/11738043/2023-06-13-5.log)

Latest log and the Mod 
https://www.curseforge.com/minecraft/mc-mods/puzzles-lib/files/4582310

**Comment by Fuzss** [comment]
I cannot reproduce this, installing the mods from these links works as intended.
https://www.curseforge.com/minecraft/mc-mods/easy-magic/files/4411041
https://www.curseforge.com/minecraft/mc-mods/puzzles-lib/files/4582310

The error you are getting is pointing to a faulty or absent installation of Puzzles Lib. Try to download the mod again.

**Comment by suerion** [comment]
I had downloaded it more then once, but the 4.4.1 does not work, we will stay on 4.4.0
