### ISSUE TITLE
[Crash]: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_239.method_17783()" because "hitResult" is null at net.minecraft.class_1665.localvar$cai000$puzzleslib$tick$0(class_1665.java:736)

### ISSUE THREAD

**Issue by noiverre** [Fuzss/puzzleslib#47]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20

### Mod Version (Required)

7.0.2

### Notes (Required)

crash occured randomly

### Crash Report (Required)

https://paste.gg/p/anonymous/b62b8d4099544054b9a7641bf8baed55

**Comment by Fuzss** [comment]
Please update Puzzles Lib to the latest version.
