### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by Tarazzo** [Fuzss/puzzleslib#49]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.4

### Mod Version (Required)

6.0.11

### Notes (Required)

1.install mutant mod on https://www.9minecraft.net/mutant-monsters-mod/
2.get the puzzleslib version 6.0.11
3.start

ps: i use feather client

### Crash Report (Required)

https://gist.github.com/Tarazzo/7c59f86f585cc10fc5a35ebf21daaae5

### latest.log (Optional)

https://gist.github.com/Tarazzo/8e5f813b13bce872c0d3167f9d07a9ff

**Comment by Fuzss** [comment]
Update Fabric Api.
