### ISSUE TITLE
[Bug]: Crash on start-up

### ISSUE THREAD

**Issue by Foxydapirate12** [Fuzss/puzzleslib#5]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

v3.3.5 Forge Resources

### Notes (Required)

Crashes on start and displays a message stating "An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience. This Crash may be caused by an invalid java Runtime configuration. Check any custom configuration settings. Exit Code: 1."
But the only thing that i changed in the java runtime settings was the max ram amount which i made 3 GB.
1. Add PuzzlesLib-v3.3.5-1.18.2-Forge-sources.jar to mod folder
2. Click Play

### latest.log (Optional)

https://gist.github.com/Foxydapirate12/e665f8e418e50ebfe962db4d55e540db

**Comment by Fuzss** [comment]
You have the wrong jar, `-sources` is for devs only, as a player get the one without it.

**Comment by Fuzss** [comment]
Closing this now as the wrong jar is probably the only issue.
