### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by FAKHORII** [Fuzss/puzzleslib#50]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20

### Mod Version (Required)

7.0.2

### Notes (Required)

Was raiding a bastion then later on the crash happened, I held a golden apple then it crashed, idk the exact cause, but it happened suddenly again later on too

### Crash Report (Required)

https://gist.github.com/FAKHORII/a32651c01b99f7c71c33a1ae6f8016de

**Comment by Fuzss** [comment]
Please update Puzzles Lib to v7.0.3.

**Comment by FAKHORII** [comment]
I did right after I posted this, sorry to disturb, and thank u for all ur work, I basically use all ur mods and I had to remove them temporarily to change my location in-game then reinstall the mods, but I lost many modded things in the possess, 
another thing I noticed in the recent 1.20 mods is that I cant configure them in mod menu, is that intended?
again, thank u so much, u are the best modder <3

**Comment by Fuzss** [comment]
Glad you like my stuff!

For in-game configs install this mod: https://legacy.curseforge.com/minecraft/mc-mods/config-menus-forge

**Comment by FAKHORII** [comment]
appreciate it so much, I forgot to add that in 1.20 and I didn't know it does what it does, much love u legend <3
