### ISSUE TITLE
[Suggestion]: Universal update procedures

### ISSUE THREAD

**Issue by PaynMusic** [Fuzss/puzzleslib#53]
### Suggestion (Required)

scripting a listener, or encouraging websites to script a listener for updates would be beneficial. "https://www.9minecraft.net/puzzles-lib/#Puzzles_Lib_1201_1194_Download_Links" is still sitting at V7.0.3 of the puzzles lib, and while the description of the download for the fabric edition of puzzles lib is noted as Minecraft 1.20.1, fabric pulls an error saying it requires 1.20, and also pulls an error for a requirement for forgeconfigapiport, which is silly on a fabric mod lol.

thank you for having a github where i can find latest releases though. it is appreciated.

**Comment by Fuzss** [comment]
Downloading the mod from websites other than CurseForge and Modrinth is neither recommended nor supported. Those other sites steal our work without providing anything in return.
