### ISSUE TITLE
[Crash]: crash with sound

### ISSUE THREAD

**Issue by Rozbiynk** [Fuzss/puzzleslib#55]
### Mod Loader (Required)

Quilt

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.0.5

### Notes (Required)

Im using raid farm, so there is many entities on the screen, and after then my game crash with puzzle lib related issue

### Crash Report (Required)

https://mclo.gs/2N52lXt

### latest.log (Optional)

https://mclo.gs/RRD62fE

**Comment by Fuzss** [comment]
Fixed in v8.0.7.
