### ISSUE TITLE
[Crash]: 6.0.11 crash on launch. Latest.log shows Mixin related error with puzzleslib mentioned.

### ISSUE THREAD

**Issue by Lieliel** [Fuzss/puzzleslib#57]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.4

### Mod Version (Required)

6.0.11

### Notes (Required)

Put/Install Puzzleslib.
No mods installed dependent on Puzzleslib.
Crash on launch. 
No crash report was generated. 
Latest.log was generated.
Redirected to the launcher with exit code 1.
Latest.log mentions "Mixin apply for mod puzzleslib failed puzzleslib.fabric.mixins.json:WolfFabricMixin from mod puzzleslib"

Removed Puzzleslib.
Now working,

Latest.log, obviously, for additional info. 

### Crash Report (Required)

Nothing generated. 

### latest.log (Optional)

https://gist.github.com/Lieliel/646c14d1196f921652bdbb03685fb071

**Comment by Lieliel** [comment]
Mod loader is Fabric.

**Comment by Fuzss** [comment]
This is likely caused by a mod conflict. The only way to find out which mod is conflicting is to remove half your mods until it works. Also 1.19.4 is no longer supported, so I'll only publish a fix for 1.20.1.

**Comment by Lieliel** [comment]
Found the conflict. The mod was Doggo Mod Overhauled. I'll be reporting this issue to the other mod author. 

This was compatible with each other back then. I don't know what changed to make a conflict. The mod hasn't been updated for 3 months. I'll inquire there instead.

Thank you and good luck!

**Comment by Fuzss** [comment]
Interesting, thanks for finding that!

I quickly checked their code and there is nothing they should change on their end. It comes down do a weirdness with the mixin framework. I'll make sure to prevent this on my end for 1.20.1, but as mentioned before 1.19.4 is no longer supported.
