### ISSUE TITLE
[Crash]: The game crashed whilst initializing game Error: java.lang.ExceptionInInitializerError: null Exit code: -1

### ISSUE THREAD

**Issue by Two-pixel** [Fuzss/puzzleslib#58]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.7

### Notes (Required)

1. Open the Minecraft launcher through the curse forge app
2. Press play
3. Wait till it loads and then it should crash and show the crash report

### Crash Report (Required)

https://gist.github.com/Fuzss/7dbd8534df46ddfa0c684162a01d2e7e

**Comment by Fuzss** [comment]
Try running your game without Sniffer+.

**Comment by Fuzss** [comment]
See #59.
