### ISSUE TITLE
[Crash]: Any 1.19 mods from Fuzs_ crashes Minecraft

### ISSUE THREAD

**Issue by BlueberryYum** [Fuzss/puzzleslib#6]
## Mod Loader

Forge

## Minecraft Version

1.19

## Mod Version

v4.0.6

### Steps
1. Place any of Fuzs_'s mods in the mods folder.
2. Press play in the launcher

### When there are no other mods
Minecraft opens and shows the loading screen. After loading finishes, Minecraft crashes.

### When there are other mods (Fullscreen enabled)
Minecraft opens and shows the loading screen before going in fullscreen. When in fullscreen, the screen turns black. Immediately after, Minecraft crashes... kinda. After crashing, the launcher doesn't open and no crash report is created.

## Crash Report

https://gist.github.com/BlueberryYum/588b19ce9b9a9424040f67cb34b06dcb

**Comment by Fuzss** [comment]
Can you try again with the latest version? And please make sure to use the latest version of Forge, they are currently pushing a lot of breaking changes.

**Comment by BlueberryYum** [comment]
Most of my mods don't support Forge versions later than 41.0.36, so I guess I'll just wait when my mods get an update.
