### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by Moosheking** [Fuzss/puzzleslib#60]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.13

### Notes (Required)

Download Regions Unexplored
Add Puzzleslib
Go into World
Place a regions unexplored sign
Watch reality collapse and crash.

### Crash Report (Required)

https://gist.github.com/Moosheking/a7ba7d794f76c0d55eb284460728bb80

**Comment by JoostMSoftware** [comment]
Hey fuzz, I also wanted to add that this is the same case for the fabric modloader.

**Comment by Moosheking** [comment]
Im sorry but I meant to hit fabric on the report

**Comment by Fuzss** [comment]
Thanks a lot for reporting, this is quite serious... Fixed now in v8.0.14.
