### ISSUE TITLE
[Crash]: Crash on launch game

### ISSUE THREAD

**Issue by wolfie0112** [Fuzss/puzzleslib#62]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.0.15

### Notes (Required)

i have enchanting infuser installed and i need puzzle lib but when i want to start the game it crashes

### Crash Report (Required)

<script src="https://gist.github.com/wolfie0112/035637de5545774ce1b7f494159cbc81.js"></script>

**Comment by Fuzss** [comment]
Please upload a properly formatted crash report, I can‘t read the file you provided.

**Comment by wolfie0112** [comment]
[crash-2023-08-02_00.17.56-fml.txt](https://github.com/Fuzss/puzzleslib/files/12238767/crash-2023-08-02_00.17.56-fml.txt)
i hope this one works

**Comment by Fuzss** [comment]
Yeah so it's just an invalid installation of Puzzles Lib. Here is a direct link to the version you need: https://legacy.curseforge.com/minecraft/mc-mods/puzzles-lib/files/4673053

**Comment by wolfie0112** [comment]
the game still crashes even after i downloaded the version you send me

**Comment by wolfie0112** [comment]
https://www.curseforge.com/minecraft/mc-mods/enderite-mod-for-forge
this mod was the problem
