### ISSUE TITLE
[Crash]: ConfigDataSet crashes when a duplicate is present

### ISSUE THREAD

**Issue by GentlemanCheesy** [Fuzss/puzzleslib#64]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.0.0

### Notes (Required)

Game crashes on opening the menu after clicking from the ESC key screen.

### Crash Report (Required)

https://pastebin.com/iAFQSsXL

**Comment by Fuzss** [comment]
Fixed in v8.0.22.
