### ISSUE TITLE
[Bug]: Shulker never drops anything

### ISSUE THREAD

**Issue by Neubulae** [Fuzss/puzzleslib#65]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.0.23

### Notes (Required)

Every mod and datapack that tweakes shulker drop no longer works either, the shulker instead drop no shells whatsoever.

**Comment by Fuzss** [comment]
Thanks for reporting. I'm unable to reproduce your issue. Shulker drops both from vanilla and data packs work fine for me in v8.0.23 on both Forge and Fabric. 

So this might be a mod conflict, it would be great if you could do some tests with a subset of your installed mods to find out if another mod is conflicting.

**Comment by Neubulae** [comment]
I will try to, but `LivingEntityMixin` from PuzzlesLib might be the culprit as disabling it seems to give me back the ability to loot shulkers. I will give a more thorough test later today.

**Comment by Neubulae** [comment]
Thanks!
