### ISSUE TITLE
[Bug]: Leftover debug code

### ISSUE THREAD

**Issue by NICKOLAS78GR** [Fuzss/puzzleslib#66]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.23

### Notes (Required)

There's some broken code from the mobplaque mod that when using the lib without that mod there are broken key controls in the options menu, additionally pressing the assigned keys displays additional broken behavior 

Examples of unwanted behavior 
![image](https://github.com/Fuzss/puzzleslib/assets/81629850/e02dfff4-8e99-445a-b34f-7ffa4b65f7bd)
when pressing j
![image](https://github.com/Fuzss/puzzleslib/assets/81629850/bf7628c1-ce4a-416c-9d8b-be50f133904a)

**Comment by Fuzss** [comment]
Thanks! Fixed in v8.0.24.
