### ISSUE TITLE
[Crash]: Incompatibility with Combatify

### ISSUE THREAD

**Issue by Afrocntrik** [Fuzss/puzzleslib#67]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.0

### Notes (Required)

Crash on initialization
Incompatibility with [Combatify](https://github.com/Alexandra-Myers/Combatify) more specifically with the Cookey Mod which is a library mod embedded in the .jar of Combatify.

### Crash Report (Required)

https://gist.github.com/Afrocntrik/62fad7d7d6e97fe1b2352ea7466395cc

**Comment by Fuzss** [comment]
This looks like an issue on Combatify's end. But cannot reproduce this on the latest versions.

Please reopen if you still get the issue after updating.
