### ISSUE TITLE
Fails to start up[Bug]: 

### ISSUE THREAD

**Issue by aanthonyssandoval1999** [Fuzss/puzzleslib#68]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

40.2.0

### Mod Version (Required)

v3.4.7+

### Notes (Required)

Any version of the mode above v3.4.7 fails to start Minecraft. I have also noticed that only a few of your other mods, Hang Glider, Mutant Monsters, and IllagerInvasion are not compatible with the only playable version, v3.4.6. Easy Anvil, Trading Posts, and Dagonal fence among a few others are the exception and work just fine so far.

**Comment by Fuzss** [comment]
Please provide your latest.log file and crash report.

**Comment by aanthonyssandoval1999** [comment]
[2023-08-25-7.log.gz](https://github.com/Fuzss/puzzleslib/files/12441194/2023-08-25-7.log.gz)

**Comment by Fuzss** [comment]
Remove structureessentials.

**Comment by aanthonyssandoval1999** [comment]
> Remove structureessentials.

Issue seems to continue. I apologize for the hard time I am giving you. https://paste.gg/p/anonymous/fc8ce13943724bd0b7f4f4ed87f516e9

**Comment by aanthonyssandoval1999** [comment]
I dont know if I need to make it an active issue for you to receive these comments, or I should wait. I would hate to annoy you by spamming this mod. Again, I apologize.

**Comment by Fuzss** [comment]
Ah, then it‘s related to this:

```
[13:56:55] [main/ERROR]: Missing or unsupported mandatory dependencies:
--
  | Mod ID: 'puzzleslib', Requested by: 'hangglider', Expected range: '[3.5.2,)', Actual version: '3.4.6'
  | Mod ID: 'forge', Requested by: 'hangglider', Expected range: '[40.2.7,)', Actual version: '40.2.0'

```

**Comment by aanthonyssandoval1999** [comment]
Ahhh so its a forge loader version issue.
