### ISSUE TITLE
[Crash]: 和doggo-mod-overhauled一起启动时，会崩溃

### ISSUE THREAD

**Issue by DSLZL** [Fuzss/puzzleslib#69]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.24

### Notes (Required)

把doggo-mod-overhauled和puzzlelib装在一起启动游戏就会崩溃
我使用了PCL2启动，但我觉得启动器应该不会有影响
但是我之前遇到过使用PCL2启动带某个mod的MC无法正常启动
而用HMCL却能正常游玩它，所以我带上了我所使用的启动器的名字
期待你的答复
还有，你的mod做的很好，兼容性非常棒，加油
（如果你看不懂翻译后的文本，请联系我，我会尽量帮助你理解，谢谢）

### Crash Report (Required)

https://gist.github.com/DSLZL/5c467d59b5bd23ba743bd5f8caee4f4f

**Comment by Fuzss** [comment]
See https://github.com/MrKacafirekCZ/doggo-mod-overhauled/pull/28
