### ISSUE TITLE
[Crash]: The game crashed whilst initializing game Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'puzzleslib'!

### ISSUE THREAD

**Issue by NoIDidntHackU** [Fuzss/puzzleslib#71]
### Mod Loader 

Fabric

### Minecraft Version 

1.20

### Mod Version

7.0.9

### Notes 

i started the game and it immediately crashed and said this:
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'puzzleslib'!
any clue why?

### Crash Report

https://www.mediafire.com/file/io9ohb3ftjhw3fd/crash-2023-09-25_15.37.25-client.txt/file

**Comment by Fuzss** [comment]
Thanks for reporting, this issue is not related to Puzzles Lib, the crash report mentions a failed Mixin from Pehkui. Puzzles Lib is only the first mod to load the problematic class.

**Comment by NoIDidntHackU** [comment]
Ok thanks, good to know
