### ISSUE TITLE
[Crash]: Incompatibility with earlyloadingscreen

### ISSUE THREAD

**Issue by some-du6e** [Fuzss/puzzleslib#73]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.24

### Notes (Required)

launch with earlyloadingscreen

### Crash Report (Required)

https://gist.github.com/some-du6e/ce54bb0f0684df82dc863880ab501615

### latest.log (Optional)

https://gist.github.com/some-du6e/ce54bb0f0684df82dc863880ab501615

**Comment by Fuzss** [comment]
This is a mixin conflict between Sodium and another mod. Puzzles Lib is simple the first mod to load the problematic class.
