### ISSUE TITLE
[Crash]: Minecraft 1.20.1 on Steam Deck crashing with Controlify when opening any container

### ISSUE THREAD

**Issue by natkos21** [Fuzss/puzzleslib#74]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.24

### Notes (Required)

1. Install both Puzzles Lib and Controlify
2. Start the game and create/open a world
3. Attempt to open inventory or any other container
4. Witness the crash and suffer

### Crash Report (Required)

https://gist.github.com/natkos21/63698d0d132281d91ccf9426692a31e7

### latest.log (Optional)

https://gist.github.com/natkos21/c6addba18bcb98acf936515c430b9b0e

**Comment by Fuzss** [comment]
Thanks for reporting!

Controlify is calling `Screen::mouseDragged` before the screen has been initialized, so it is to be expected that some required fields have not had their proper value set yet. This is better fixed on Controlify's end.

**Comment by Fuzss** [comment]
See https://github.com/isXander/Controlify/issues/174.

**Comment by natkos21** [comment]
Thanks for Your answer!
That's kind of a bummer, cause Controlify's author is on a kinda-break rn. And the issue You linked is also mine lol
But guess I'll just have to wait for the fix

**Comment by Fuzss** [comment]
Come on our Discord (https://lunapixel.studio/discord) and ping me there, I'll send you a custom Puzzles Lib version with a temporary workaround.

**Comment by natkos21** [comment]
Pinged You

**Comment by Fuzss** [comment]
Temporary workaround: https://cdn.discordapp.com/attachments/917550806922846299/1163179378058993805/PuzzlesLib-v8.0.37.479-1.20.1-Fabric.jar?ex=653ea236&is=652c2d36&hm=77bb9a86aeab2ed7a8a9effd156b266e78b781bff63fc7b983c18d6bce07c3b3&
