### ISSUE TITLE
[Crash]: Game crashes when I open a chest and "Not enough crashes" says puzzles lib is responsible for it.

### ISSUE THREAD

**Issue by cobaltlol** [Fuzss/puzzleslib#76]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.0.24

### Notes (Required)

1. Find a generated chest (this crash in question happened in a modded pillager outpost so I'm not sure it applies to other chests)
2. Open the chest
3. Game freezes and crashes

### Crash Report (Required)

https://pastebin.com/P3bX6T6m

### latest.log (Optional)

https://pastebin.com/fPaBcfr2

**Comment by cobaltlol** [comment]
Also, opening BASICALLY anything causes this crash, and I've noticed right after rejoining following a crash I lose my skin model, and no items dropped have models anymore theyre just there, you can still pick them up and stuff just no models

**Comment by cobaltlol** [comment]
#Print menu type to game chat whenever a new menu screen is opened. Intended for finding menu types to be added to "menu_blacklist".
debug_container_types = false
#Print screen identifier to game chat or log file whenever a new screen is opened. Intended for finding screens to be added to "font_color_blacklist".
debug_all_screens = false
#Exclude certain menus from showing the dark mode switcher. Useful when the box intersects other screen elements.
menu_blacklist = []
#Specifies gui paths and resources to darken.
#End a path using '*' as a wildcard char to include every file (no nested directories) from that directory.
#Begin with a namespace or skip namespace to apply to all namespaces.
#Begin with '!' to exclude matches, list those exclusions after entries that would otherwise include them.
paths = ["textures/gui/*", "!minecraft:textures/gui/icons.png", "!minecraft:textures/gui/options_background.png", "textures/gui/container/*", "minecraft:textures/gui/container/creative_inventory/*", "trinkets:textures/gui/slots/*", "craftingtweaks:gui.png", "dankstorage:textures/container/gui/*", "ae2:textures/guis/*", "!modmenu:textures/gui/mod_configuration.png", "!dynamiccrosshair:textures/gui/crosshairs.png"]
#Do not add the dark mode toggle buttons to the top of every menu.
hide_in_game_switcher = false
#Screens to add a dark mode toggle button to, so that toggling is possible outside of inventory menus.
#Allowed Values: NONE, TITLE_SCREEN, PAUSE_SCREEN, BOTH
dark_mode_toggle_screens = "BOTH"
#Exclude certain screens from being affected by any text color alterations.
font_color_blacklist = ["chat_screen.title", "sign.edit", "hanging_sign.edit"]
#Use a dark theme for the configuration screens.
dark_theme = true
#Percentage of original interface brightness to apply.
#Range: 0.0 ~ 1.0
texture_darkness = 0.5
#The minimum brightness value of font while dark mode is enabled.
#Range: 0.0 ~ 1.0
font_brightness = 0.75
#Algorithm selector for darkening interface pixels.
#Allowed Values: GRAYSCALE_AND_HSP, HSP, GRAYSCALE_AND_HSL, HSL, GRAYSCALE_AND_LINEAR, LINEAR
darkening_algorithm = "GRAYSCALE_AND_HSP"

**Comment by cobaltlol** [comment]
Deleting mindful darkness config seems to have fixed it since I changed some things in it before and it crashes with those configs

**Comment by Fuzss** [comment]
The crash report points to `menu_blacklist` containing an invalid value which I don't see in the config you sent though.
I'll make sure this won't make the game crash / behave weirdly in the future.

**Comment by cobaltlol** [comment]
Yes because a bit before you first replied I deleted the mindful darkness config because that was the only thing i modified and then you replied so I launched minecraft again so it would make that new config

**Comment by Fuzss** [comment]
An input error like this will no longer result in a crash as of v8.1.0.
