### ISSUE TITLE
[Crash]: Crash on startup with v8.1.0

### ISSUE THREAD

**Issue by mpustovoi** [Fuzss/puzzleslib#78]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.1.0

### Notes (Required)

I have a bunch of mods installed, so it won't be so easy to reproduce it.
I've only updated Puzzles Lib to v8.1.0 I got a Fabric Loader window with crash `due to errors, provided by 'advanced_runtime_resource_pack'`.
I thought it was related to Distinguished Potions v8.0.2, but even without this mod Minecraft can't launch.
Minecraft didn't create a crash report, so I just copied the issue from the Loader window.

### Crash Report (Required)

https://gist.github.com/mpustovoi/09098b25aed1dfeb8b45c6aad1a9362f

### latest.log (Optional)

https://gist.github.com/mpustovoi/c06f0b862402b08af11e08b0aee6b0ed

**Comment by TheWitherlord** [comment]
same issue but with forge

**Comment by TheWitherlord** [comment]
Same issue here with the latest forge version
https://gist.github.com/TheWitherlord/7ec3f653b83825f2ab7e9fb77b968e66

**Comment by Vinzound** [comment]
I have the same problem too :(

**Comment by Fuzss** [comment]
@Vinzound Please provide a log and crash-report.

**Comment by Fuzss** [comment]
@mpustovoi Does v8.1.1 resolve your issue? If it doesn't please post a new log and crash.

**Comment by Zedrimar** [comment]
I know this is a bit random, but is there any chance that there could still be a version to run in neoforge? I personally prefer neoforge since it's a lot less buggy in my opinion.

Not sure if it helps or not, but I did try loading the latest version of puzzles lib (after tweaking the mods.toml inside the jar file) with stylish effects and it ran just fine in the latest version of neoforge.

**Comment by Fuzss** [comment]
@Zedrimar Neo support was fixed now in v8.1.2. Thanks for reporting!

**Comment by Zedrimar** [comment]
@Fuzss Awesome! Thank you!

**Comment by Fuzss** [comment]
Great! Closing this now.
