### ISSUE TITLE
[Bug]: because the return value of "net.minecraft.class_1309.getTouchingFluid()" is null at fuzs.puzzleslib.impl.event.FabricEventImplHelper.tickAirSupply(FabricEventImplHelper.java:47)

### ISSUE THREAD

**Issue by stunlocked1** [Fuzss/puzzleslib#80]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.1.0 - 8.1.2

### Notes (Required)

https://gist.github.com/stunlocked1/599738559e90a6e6a8fc2c68aa6095f8
It kicks player and kills a bunch of  other entities because of this thing that mentions puzzle lib. Sometimes it crashes sometimes just hangs. I also downgraded puzzles lib to 8.0.24 and the issue is gone

### latest.log (Optional)

https://gist.github.com/stunlocked1/599738559e90a6e6a8fc2c68aa6095f8

**Comment by Fuzss** [comment]
Please report this to [Star](https://github.com/AlphaMode/Star).

**Comment by Fuzss** [comment]
Removed that part from Puzzles Lib now, it has been moved to my Thin Air mod where it is required. So only Thin Air is now incompatible with Star and not everything that depends on Puzzles Lib.
