### ISSUE TITLE
[Bug]: can't start minecraft

### ISSUE THREAD

**Issue by ipiiia** [Fuzss/puzzleslib#81]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.1.5

### Notes (Required)

stuck on loading screen

no log

**Comment by Fuzss** [comment]
Send the latest.log or debug.log. Otherwise I can‘t help you.

**Comment by ipiiia** [comment]
> Send the latest.log or debug.log. Otherwise I can‘t help you.

Sorry it was probably a problem with DiagonalFences and now it's fixed.
