### ISSUE TITLE
[Bug]: [v8.1.8-1.20.1] Server hang/fail to load

### ISSUE THREAD

**Issue by c0gd1s** [Fuzss/puzzleslib#82]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.1.8

### Notes (Required)

When updating to 8.1.8 my server hangs during startup, reverting to 8.1.7 works fine. Looks like the conflict is between it and midnightlib, maybe because midnightlib also supports a mod that adds controller functionality.

### latest.log (Optional)

https://gist.github.com/c0gd1s/fd9ba0de0f4826d248742643d3d988e0

**Comment by Fuzss** [comment]
Midnight Lib and Puzzles Lib both don't seem to have anything to do with this issue.
For Puzzles Lib specifically; nothing changed for the Forge version from 8.1.7 to 8.1.8.

Try removing the Copperative mod for now, the issue seems to be related to that mod judging from the crash report.

**Comment by c0gd1s** [comment]
Totally my bad, wrong report. Let me try to recreate the issue.

**Comment by c0gd1s** [comment]
https://gist.github.com/c0gd1s/1e8ca25ca076669780b448ed8ac79a0c#file-gistfile1-txt

**Comment by Fuzss** [comment]
Ah yes. Fixed in v8.1.1 of Permanent Sponges.

**Comment by c0gd1s** [comment]
Ok cool thanks, your mods are awesome

**Comment by Fuzss** [comment]
Thanks :D
