### ISSUE TITLE
[Bug]: performance issue

### ISSUE THREAD

**Issue by Flexz9** [Fuzss/puzzleslib#84]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.24

### Notes (Required)

https://spark.lucko.me/LC20GSuBX8

When 2 players are afk, this library is using 10% of each tick when we only have easy shulkers installed that this library is required for.
What we found in the spark link is that funnels from create get slowed down because of this library. This should not be the case.

**Comment by Fuzss** [comment]
Hmm, there is nothing going on in that code honestly. Just iterating over a very small map (should have two entries only if ESB is all you have installed).

I rewrote that piece of code a little, maybe it helps: https://cdn.discordapp.com/attachments/917550806922846299/1172996203491893308/PuzzlesLib-v8.1.8.548-1.20.1-Forge.jar
