### ISSUE TITLE
[Crash]: After updating, can no longer join previous worlds or create new ones

### ISSUE THREAD

**Issue by 630R63** [Fuzss/puzzleslib#85]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.1.8

### Notes (Required)

1. Create a world using Forge 47.1.44, PuzzleLib 8.0.24, Diagonal Fences 8.0.1, Diagonal Windows 8.0.1
2. Exit the game
3. Update the mods to PuzzleLib 8.1.8, Diagonal Fences 8.1.2, Diagonal Windows 8.1.2
4. Start the game
5. Try to join previous created world (get error that world is corrupted)
6. Try to create new world (game crashes)

### Crash Report (Required)

https://gist.github.com/630R63/3086b5b79d8878fbb6beecb366b9536e

### latest.log (Optional)

https://gist.github.com/630R63/fd71d64e092beae39ee812cf41b77536

**Comment by Fuzss** [comment]
No worries, the world is not corrupted. It's a simple data pack error. Please try this Puzzles Lib version and send the new crash report: https://cdn.discordapp.com/attachments/917550806922846299/1173580038625558528/PuzzlesLib-v8.1.8.549-1.20.1-Forge.jar

**Comment by 630R63** [comment]
Thanks for getting back to me so fast!

Tried it with the provided jar file:
![image](https://github.com/Fuzss/puzzleslib/assets/6078866/fb8a9333-325a-4910-9140-c471a1b54cb8)
If I go into safe mode:
![image](https://github.com/Fuzss/puzzleslib/assets/6078866/1ed899f8-1316-4d72-a0c7-0630a7127fa3)

Here is the new latest.log: https://gist.github.com/630R63/d7cd8fd6ac15bf476c42be9a650bbc51
And the latest crash report: https://gist.github.com/630R63/02a98f55018f4487571c8e9027cf0851

Ok, now it says that some block from Chipped is missing?

**Comment by Fuzss** [comment]
Fixed in v8.1.19.
