### ISSUE TITLE
[Crash]: Crash on entering world

### ISSUE THREAD

**Issue by ChromaPIE** [Fuzss/puzzleslib#87]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

PuzzlesLib-v8.1.8-1.20.1-Fabric

### Notes (Required)

Title

### Crash Report (Required)

https://mclo.gs/mi6lu2L

**Comment by Fuzss** [comment]
See https://github.com/AlphaMode/Star/issues/2.
