### ISSUE TITLE
[Crash]: Spending time in the creative inventory crashes

### ISSUE THREAD

**Issue by LenKagamine** [Fuzss/puzzleslib#88]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.4.3

### Notes (Required)

1. Open creative menu
2. Click through the different tab pages
3. Crash

### Crash Report (Required)

https://gist.github.com/LenKagamine/0e048f89b09aefc34f38e2093faf33a8

### latest.log (Optional)

https://gist.github.com/LenKagamine/5e5b12eb1a6073353fcb290d008f66a0

**Comment by Fuzss** [comment]
See https://github.com/Fuzss/stoneworks/issues/5.
