### ISSUE TITLE
[Bug]: Puzzleslib

### ISSUE THREAD

**Issue by PaladinFallen** [Fuzss/puzzleslib#9]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.1

### Mod Version (Required)

4.1.1

### Notes (Required)

Start the game and read the log file

### latest.log (Optional)

https://gist.github.com/PaladinFallen/f20f8212f29a3c8c26785c824623bbdc

**Comment by Fuzss** [comment]
Should be fixed in v4.1.2. Please reopen if it comes back.
