### ISSUE TITLE
[Crash]: PuzzlesLib incompatible with Hephaestus.

### ISSUE THREAD

**Issue by CoderXL1** [Fuzss/puzzleslib#91]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.1.11

### Notes (Required)

It crashes when entering a world. It says the game crashed because an entity was not working. The entity might be pig, bat or any creature in the game.

### Crash Report (Required)

https://paste.gemwire.uk/view/99c3f03f

**Comment by Fuzss** [comment]
See #80.
