### ISSUE TITLE
[Crash]: Puzzle libs just crashes

### ISSUE THREAD

**Issue by JustFoxx** [Fuzss/puzzleslib#94]
### Mod Loader (Required)

NeoForge

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

20.4.142-beta

### Other Mods Involved (Required)

No

### Notes (Required)

Just starting the game and crashes at start time

### Crash Report (Required)

https://mclo.gs/aYQHPl8

### latest.log (Optional)

https://mclo.gs/hb2uXUm

**Comment by Fuzss** [comment]
Thanks for reporting. Fixed in v20.4.14.

**Comment by ZerJ704** [comment]
> Thanks for reporting. Fixed in v20.4.14.

Hi Fuzcss, I tried it with this v20.4.14 and v20.4.15 but I have some similar crashes for fabric 1.20.4
