### ISSUE TITLE
[Crash]: Puzzle Lib Crash?

### ISSUE THREAD

**Issue by ZerJ704** [Fuzss/puzzleslib#96]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

v20.4.14 and v.20.4.15

### Other Mods Involved (Required)

Yes

### Notes (Required)

I start the game and the crash happen

### Crash Report (Required)

https://gist.github.com/ZerJ704/f9a5dbb0e7a4db88e08e1873cb3d6a01

### latest.log (Optional)

https://gist.github.com/ZerJ704/a3a1bce998f518e1af1b1f742b078608

**Comment by Fuzss** [comment]
Report this to extra-enchantments-and-curses. The library they are using is broken.

**Comment by ZerJ704** [comment]
> Report this to extra-enchantments-and-curses. The library they are using is broken.

Oh okay, thank u so much. Sorry for this, I thought it was puzzle lib
