### ISSUE TITLE
[Crash]: ViaFabricPlus

### ISSUE THREAD

**Issue by ShayBox** [Fuzss/puzzleslib#98]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

v20.4.23

### Other Mods Involved (Required)

Yes

### Notes (Required)

I'm using the Fabulously Optimized v5.8.0-beta.10 mod pack from Modrinth, but the issue is with ViaFabricPlus & PuzzlesLib, it works with ViaFabric.

### Crash Report (Required)

https://pastebin.com/QJjw9VG6

**Comment by Fuzss** [comment]
ViaFabric uses Mixins that are incompatible with other mods, there is nothing I can do about it on my end.

**Comment by ShayBox** [comment]
It's only ViaFabricPlus, ViaFabric works

**Comment by Fuzss** [comment]
That'S what I meant.

**Comment by Fuzss** [comment]
This is already fixed indev on their end, you'll just have to wait for the next version.
