### ISSUE TITLE
Crashing on Launch

### ISSUE THREAD

**Issue by kualatoni** [Fuzss/puzzleslib#99]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

1.20.4 onwards

### Other Mods Involved (Required)

Yes

### Notes (Required)

Game crashes on startup. ngl I'm running 30+ mods sooooo

### Crash Report (Required)

https://gist.github.com/kualatoni/15d14d43800f084136f1cc48619c422b

**Comment by Fuzss** [comment]
Report this to enchantmentsplus, the reach-entity-attributes library they are using is broken.
